FROM node:22-alpine AS builder

# Instala dependências do sistema necessárias para o Prisma
RUN apk add --no-cache libc6-compat openssl

WORKDIR /app

# Copia os arquivos de configuração do projeto
COPY package.json yarn.lock* tsconfig.json ./

# Copia a pasta do Prisma e o código fonte necessário para o seed
COPY prisma ./prisma
COPY src ./src

# Instala todas as dependências (necessário para o ts-node e typescript rodarem o seed)
RUN yarn install --frozen-lockfile

# Gera o cliente do Prisma
RUN npx prisma generate

FROM node:22-alpine
RUN apk add --no-cache openssl

WORKDIR /app

# Copia apenas o necessário do builder para a imagem final
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/tsconfig.json ./
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/src ./src

# Comando padrão que será executado quando o container do Job iniciar
CMD ["sh", "-c", "npx prisma db push && yarn db:seed"]
